pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Status - Build Start') {
            steps {
                // #800080 = purple
                slackSend color: '#800080', message: "Starting Job: ${env.JOB_NAME} (Build ${env.BUILD_NUMBER})"
            }
        }
       stage('Build') {
            steps {
                sh 'mvn -B -DskipTests package'
            }
        }
        stage('Software Composition Analysis') {
            steps {
                dependencyCheckAnalyzer datadir: '/home/hirosh7/OWASP_NVD_Updates', hintsFile: '',
                includeCsvReports: false, includeHtmlReports: true, includeJsonReports: false,
                includeVulnReports: false, isAutoupdateDisabled: true, outdir: '.', scanpath: '.',
                skipOnScmChange: false, skipOnUpstreamChange: false, suppressionFile: '', zipExtensions: ''
            }
            post {
                always {
                     dependencyCheckPublisher canComputeNew: false, defaultEncoding: '', healthy: '',
                    pattern: '**/dependency-check-report.xml', unHealthy: ''
                }
                failure {
                    // #ff0000 = red
                    slackSend color: '#ff0000', message: "Failed during SCA stage"
                }
           }
        }
        stage('SonarQube Analysis') {
            environment {
                SCANNER_URL = 'http://192.168.0.25:8888'
            }
            steps {
                slackSend color: '#439FE0', message: "Starting SAST scan with SonarQube"
               withSonarQubeEnv('Jenkins SonarQube') {
                   sh 'mvn sonar:sonar -Dsonar.host.url=${SCANNER_URL}'
               }
            }
            post {
                success {
                    slackSend color: '#00ff00', message: "SAST scan completed successfully"
                }
                failure {
                    slackSend color: '#ff0000', message: "SAST scan Failed "
                }
            }
        }
        stage('SonarQube Q-Gate Check') {
           steps {
             timeout(time: 2, unit: 'MINUTES') {
                  waitForQualityGate abortPipeline: true
             }
           }
        }
        stage('Status - Build Complete') {
            steps {
                slackSend color: '#00ff00', message: "${env.JOB_NAME} - Build Complete"
            }
        }
        stage('OWASP ZAP Scan') {
                steps {
                    sh 'echo Scanning with OWASP ZAP'
                }
        }
    }
}
